Add circuit dag
HQSquantumsimulations/qoqo pull request #319
Opened 2022-08-04 14:36 UTC by mlodi-hqs

2022-08-09 08:44 UTC, nfwvogt requested changes
Looks good overall, but some changes could make the API more general.

Also for testing, once the reverse `From<CircuitDag> for Circuit` is implemented we should add a round-trip test with Circuit -> CircuitDag -> Circuit with a random circuit containing CNOT and PauliX. The result of the circuit can be calculated classically and we can compare the result of the original circuit and the round trip circuit.

2022-08-09 08:44 UTC, nfwvogt commented on roqoqo/tests/integration/circuitdag.rs
> +
Could you also add a test for edges if we have a all-qubit-operation in the circuit as this is a special case?

2022-08-09 13:03 UTC, mlodi-hqs commented on roqoqo/tests/integration/circuitdag.rs
> +        .contains_edge(ind1.unwrap().into(), ind2.unwrap().into()));
They are Option<usize>, so they need it.

2022-08-16 07:30 UTC, nfwvogt approved these changes
Looks good to me

2022-08-22 07:02 UTC, merged