Remapping Validity Check Feature
HQSquantumsimulations/qoqo pull request #550
Opened 2024-03-08 10:39 UTC by mlodi-hqs

* Added `unstable_remapping_validity_check` feature

2024-03-11 09:16 UTC, mlodi-hqs commented
Now updated to `alpha.2`

2024-03-11 16:41 UTC, kbarkhqs commented on roqoqo/src/operations/pragma_operations.rs
Could you add tests for this behaviour with the feature? (for PragmaStartDecompositionBlock, PragmaControlledCircuit and PragmaChangeDevice)

2024-03-11 16:42 UTC, kbarkhqs commented on roqoqo/src/operations/analog_operations.rs
Also here, I would suggesting adding tests

2024-03-11 16:42 UTC, kbarkhqs commented on roqoqo/src/operations/measurement_operations.rs
Same here, I would suggest adding tests to check the behaviour is correct

2024-03-11 16:43 UTC, kbarkhqs commented on roqoqo-derive/src/substitute.rs
Could you add a test for one of the structs that derives this, to check it?

2024-03-11 16:43 UTC, kbarkhqs commented on roqoqo-derive/src/substitute_modes.rs
Could you add a test for one of the structs that derives this, to check it?

2024-03-11 16:43 UTC, kbarkhqs requested changes
Further unittests for completeness would be helpful

2024-03-12 12:02 UTC, mlodi-hqs commented
The runners will only run `cargo test --no-default features`, but locally `cargo test --no-defeault-features --features unstable_remapping_validity_check ` works too.

2024-03-12 15:42 UTC, kbarkhqs approved these changes

2024-06-06 14:50 UTC, mlodi-hqs commented
No longer necessary as I got around the problem in another way.

2024-06-06 14:50 UTC, closed without merging