Bump version
HQSquantumsimulations/qoqo pull request #564
Opened 2024-05-23 15:17 UTC by kbarkhqs

2024-05-23 15:44 UTC, dberthault requested changes

2024-05-23 15:44 UTC, dberthault commented on qoqo/tests/integration/noise_models/overrotation.rs
> +            .call_method0("__deepcopy__")
```suggestion
            .call_method1("__deepcopy__", ("",))
```

2024-05-23 15:44 UTC, dberthault commented on qoqo/tests/integration/noise_models/overrotation.rs
> +            .call_method0("__deepcopy__")
```suggestion
            .call_method1("__deepcopy__", ("",))
```

2024-05-24 07:54 UTC, dberthault approved these changes

2024-05-24 08:23 UTC, nfwvogt approved these changes

2024-05-24 08:23 UTC, merged